name: ajParkour
version: "@VERSION@"
author: ajgeiss0702
description: Randomly generated parkour
website: https://about.ajg0702.us/project/ajParkour
main: us.ajg0702.parkour.ParkourPlugin
softdepend: [PlaceholderAPI, WorldEdit]
api-version: 1.13

commands:
  ajParkour:
    description: ajParkour commands
    aliases: [ap, ajp, ajpk, apk]
    usage: "/ajParkour, /ap, /ajp, /ajpk, /apk"
